"""
Train a surrogate model: r_bend -> P99 springback, on the campaign-level
data generated by generate_training_data.py.

Deliberately a simple model (GradientBoostingRegressor) rather than a
neural network -- per project notes, simplicity reads better than
sophistication for a 1D regression problem, and the point of this project
is the workflow (expensive campaign -> fast surrogate -> accelerated
search), not surrogate-model sophistication.

Reports R^2 and MAPE against a held-out test split -- this is the
"surrogate fit quality" honesty check flagged in project notes (borrowed
from the surrogate-model-learning OSS pattern of reporting real numbers,
not just asserting the surrogate works).
"""
from __future__ import annotations

import csv
import pickle
import time
from pathlib import Path

import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_percentage_error, r2_score
from sklearn.model_selection import train_test_split

DEFAULT_DATA_PATH = Path("data/training_data.csv")
DEFAULT_MODEL_PATH = Path("data/surrogate_model.pkl")


def load_training_data(path: Path = DEFAULT_DATA_PATH) -> tuple[np.ndarray, np.ndarray]:
    rows = []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append((float(row["r_bend"]), float(row["p99_springback_mm"])))
    r = np.array([row[0] for row in rows]).reshape(-1, 1)
    p99 = np.array([row[1] for row in rows])
    return r, p99


def train_surrogate(
    data_path: Path = DEFAULT_DATA_PATH,
    model_path: Path = DEFAULT_MODEL_PATH,
    test_size: float = 0.2,
    seed: int = 42,
) -> dict:
    """
    Fit GradientBoostingRegressor on r -> P99 springback, evaluate on a
    held-out split, save the trained model, return a metrics dict
    (R^2, MAPE, training data size, timing for both training and a
    representative batch of surrogate predictions).
    """
    r, p99 = load_training_data(data_path)
    r_train, r_test, p99_train, p99_test = train_test_split(
        r, p99, test_size=test_size, random_state=seed
    )

    model = GradientBoostingRegressor(random_state=seed)

    t0 = time.perf_counter()
    model.fit(r_train, p99_train)
    train_time = time.perf_counter() - t0

    predictions = model.predict(r_test)
    r2 = r2_score(p99_test, predictions)
    mape = mean_absolute_percentage_error(p99_test, predictions)

    # Timing comparison: predict across a dense sweep, compare to the
    # physics campaign time for the same sweep (see generate_training_data.py).
    dense_r = np.linspace(r.min(), r.max(), 200).reshape(-1, 1)
    t0 = time.perf_counter()
    model.predict(dense_r)
    surrogate_sweep_time = time.perf_counter() - t0

    model_path.parent.mkdir(parents=True, exist_ok=True)
    with open(model_path, "wb") as f:
        pickle.dump(model, f)

    metrics = {
        "n_training_samples": len(r_train),
        "n_test_samples": len(r_test),
        "r2": r2,
        "mape": mape,
        "train_time_s": train_time,
        "surrogate_200_radius_sweep_s": surrogate_sweep_time,
    }
    return metrics


if __name__ == "__main__":
    metrics = train_surrogate()

    print("Surrogate training complete.")
    print(f"  Training samples: {metrics['n_training_samples']}")
    print(f"  Test samples:     {metrics['n_test_samples']}")
    print(f"  R^2 (held-out):   {metrics['r2']:.5f}")
    print(f"  MAPE (held-out):  {metrics['mape']:.4%}")
    print(f"  Training time:    {metrics['train_time_s']:.3f}s")
    print()
    print(f"  Surrogate prediction across 200 radii: "
          f"{metrics['surrogate_200_radius_sweep_s']*1000:.2f}ms")
    print(f"  (physics campaign across the same 200 radii took ~9.4s "
          f"in generate_training_data.py -- see README for the honest "
          f"campaign-vs-surrogate comparison)")
